firebase/fastlane-plugin-firebase_app_distribution

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- spec/firebase_app_distribution_action_spec.rb
Users may set the firebase_cli_path parameter via `which firebase` (as seen in https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution/issues/4), so we should chomp the input value as well.
> Chomp firebase_cli_path parameter

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_error_message.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_helper.rb
- spec/firebase_app_distribution_action_spec.rb
Adding in File support for the parameters. This allows users to pass in a file as a parameters for either for access or for release notes.
> File support

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
Because it's set as required, it will always use the default value and try to verify that the tool is installed. This change makes it optional and removes the validation since we never use it anyway.
We should follow this up with some more cleanup to remove the dead code surrounding this as well as to add a message saying that the firebase_cli_path parameter is deprecated, if it is set by the user.
> Remove dependency on Firebase CLI being installed

- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- spec/firebase_app_distribution_api_client_spec.rb
Got feedback from a customer that we were talking about 'IPA' even though they are building an Android app.
> Fall back to 'APK/IPA' if platform is unknown

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
Prints the message `Using deprecated option: '--firebase_cli_path' (This plugin no longer uses the Firebase CLI)` when the parameter is used:
This also removes an unused method that was originally used by this parameter.
> Deprecate the firebase_cli_path param

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- spec/firebase_app_distribution_action_spec.rb
- spec/firebase_app_distribution_api_client_spec.rb
- spec/firebase_app_distribution_auth_client_spec.rb
- spec/firebase_app_distribution_helper_spec.rb
Previously we relied only on the lane context to get the platform. This was causing a surprising number of `unknown` platforms to show up in our metrics. In the Firebase CLI we use the binary file type exclusively to determine the platform. Here we'll use it as a backup if the lane context isn't set.
This also:
- Fixes some failing tests (for me locally, anyway) due to not calling through when mocking the `File` object
- Removes the unnecessary memoization of the lane platform, since it's just a hash lookup
> Use binary path to determine path, if none set

- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- spec/firebase_app_distribution_api_client_spec.rb
Should fix https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/146
I was able to reproduce the issue on Windows, and this fixes it. The issue is probably the EOL conversion:
```
"b"  |  Binary file mode (may appear with
|  any of the key letters listed above).
|  Suppresses EOL <-> CRLF conversion on Windows. And
|  sets external encoding to ASCII-8BIT unless explicitly
|  specified.
```
Tested by uploading new iOS and Android distributions and verifying that the uploads succeed and the apps function correctly.
> Fix binary upload on Windows

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- spec/firebase_app_distribution_action_spec.rb
Previously if no platform is set, we would get the binary path using a combination of the parameters passed in, and searching for an IPA or APK. Then we would determine the platform from the binary path.
This leads to bugs like https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/151, because if for example we find an IPA in the root directory, we will upload that binary regardless of whether or not apk_path is set.
It will be more reliable to get the platform from the app ID, and they use that to determine which path to use.
> Get binary path from platform, and platform from app ID

- lib/fastlane/plugin/firebase_app_distribution/version.rb
This version contains a fix for multi-platform environments: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/pull/152 (which addresses https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/151)
> Bump version for pre-release v0.2.2.pre.1

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- spec/firebase_app_distribution_action_spec.rb
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/pull/152 introduced a bug where if you don't set the app ID, we try to use the platform before the variable has been set.
Instead, we really just need to see if xcode_archive_path is set. However, because some folks might be building in cross-platform environments, we double check that the platform is not set to Android in the lane context.
> Do not use platform before it's initialized

- lib/fastlane/plugin/firebase_app_distribution/version.rb
Includes:
- Fix for https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/154
- Adds the `--googleservice_info_plist_path` parameter: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/pull/46
> Version bump for 0.2.2.pre.2

- lib/fastlane/plugin/firebase_app_distribution/client/error_response.rb
- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_error_message.rb
- spec/firebase_app_distribution_api_client_spec.rb
Parse error response of call to create release notes and display error message.
> Show error message when posting release notes fails

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
Before `v.0.2.0` we passed the `debug` parameter to the Firebase CLI and it printed verbose output. Now that there is no longer a dependency on the Firebase CLI , this parameter wasn't being used. This change adds support for debug logging the request and the response body.
> Add support for debug logging

- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- spec/firebase_app_distribution_api_client_spec.rb
We are incorrectly assuming that 404's returned from calls to other methods mean an invalid app id was used. This is only true for calls to `get_app`.
> Only print invalid app message on 404's returned from get_app call

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/client/app.rb
- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_error_message.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_helper.rb
- lib/fastlane/plugin/firebase_app_distribution/version.rb
- spec/firebase_app_distribution_action_spec.rb
- spec/firebase_app_distribution_api_client_spec.rb
- spec/firebase_app_distribution_helper_spec.rb
This PR refactors the code and makes the following changes:
- Adds an `android_artifact_path` and an `android_artifact_type` parameter. 
- Adds error handling for AAB's
- Adds tests for the run method in the action class
The process to determine where to get the binary is similar to how the gradle plugin works:
- If it's an android app and `android_artifact_path` or `apk_path` (which I deprecated) is set, it uses those values.
- If they aren't set and `android_artifact_type` is set to `AAB` it attempts to infer a path to the `AAB`.
- Otherwise it attempts to infer a path to the `APK`.
> Add support for uploading AAB's

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_udids.rb
- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- lib/fastlane/plugin/firebase_app_distribution/version.rb
- spec/firebase_app_distribution_api_client_spec.rb
- spec/firebase_app_distribution_get_udids_spec.rb
Example:
```
firebase_app_distribution_get_udids(
app: "1:1234567890:ios:1234567890abcdef",
firebase_cli_token: "<token value>",
output_file: "/Users/myusername/tester_udids.txt",
)
```
Output (with debug enabled):
```
[09:23:15]: Driving the lane 'download_udids' 🚀
[09:23:15]: -------------------------------------------------
[09:23:15]: --- Step: firebase_app_distribution_get_udids ---
[09:23:15]: -------------------------------------------------
[09:23:15]: Authenticating with --firebase_cli_token parameter
[09:23:15]: 🔐 Authenticated successfully.
D, [2021-03-23T09:23:15.680917 #87440] DEBUG -- request: GET https://firebaseappdistribution.googleapis.com/v1alpha/apps/1:1234567890:ios:1234567890abcdef/testers:getTesterUdids
D, [2021-03-23T09:23:16.117578 #87440] DEBUG -- response: …
```
> Add new action to download tester UDIDs

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- spec/firebase_app_distribution_api_client_spec.rb
If after 2 minutes the status shows the binary is still being processed, then exit with an error. Otherwise we are hiding the fact that that distribution may not be uploaded successfully.
> Exit with a non-zero status code if upload does not finish

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_add_testers_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_remove_testers_action.rb
Currently fails with the following error:
```
[!] Implementing `is_supported?` for all actions is mandatory. Please update Fastlane::Actions::FirebaseAppDistributionAddTestersAction (FastlaneCore::Interface::FastlaneCrash)
```
> Add is_supported? to add/remove tester actions

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_add_testers_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_remove_testers_action.rb
- spec/firebase_app_distribution_add_testers_action_spec.rb
- spec/firebase_app_distribution_remove_testers_action_spec.rb
Prefer `project_number` to `project` to ensure developers don't use project ID
> Rename project param to project_number

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_auth_client.rb
- spec/firebase_app_distribution_auth_client_spec.rb
This will help troubleshoot in cases like https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/215.
Before:
```
[!] App Distribution could not generate credentials from the service credentials file specified. Service Account Path: <path>
```
After:
```
[!] App Distribution could not generate credentials from the service credentials file specified. Service Account Path: <path>
Details:
Authorization failed.  Server message:
{"error":"invalid_grant","error_description":"Invalid grant: account not found"}
Response status: 400
```
> Print details of service account auth errors

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_add_testers_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_remove_testers_action.rb
- spec/firebase_app_distribution_add_testers_action_spec.rb
- spec/firebase_app_distribution_remove_testers_action_spec.rb
Prefer `string_to_array` instead of `split` since it handles whitespaces and handle case where `nil` or `[]` is returned from `string_to_array`
> Handle whitespaces and empty email arrays

- lib/fastlane/plugin/firebase_app_distribution/version.rb
Includes new `firebase_app_distribution_get_latest_release` action.
> Bump version to 0.3.2.pre.1

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_latest_release.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_udids.rb
Use examples that don't look like actual app IDs, to reduce the chances that someone copies the example verbatim and gets a 403 because they don't have access to the project.
> Update code examples

- lib/fastlane/plugin/firebase_app_distribution/version.rb
Version `0.3.2.pre.1` is looking good. This release will address https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/25.
> Bump version to 0.3.2

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_auth_client.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_error_message.rb
- spec/firebase_app_distribution_auth_client_spec.rb
Hoping to help folks resolve their own refresh token issues (see https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/178). This change:
- Prompts developers to set the debug parameter to true to get more info
- In debug mode, prints out the refresh token used
Example failure using service credential file, with `debug: false`:
```
[17:40:57]: App Distribution could not generate credentials from the service credentials file specified: "/path/to/bad.json". For more information, try again with firebase_app_distribution's "debug" parameter set to "true".
```
... and `debug: true`:
```
[18:08:09]: App Distribution could not generate credentials from the service credentials file specified: "/path/to/bad.json"
Authorization failed.  Server message: …
```
> Improve error messages when failing to get access token

- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_helper.rb
- spec/firebase_app_distribution_helper_spec.rb
In response to #266 we should only _trim_ the whitespaces from the individual values in a comma separated string
> Trim individual values from comma separate strings

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_login.rb
Screenshot of proposed message when running `bundle exec fastlane run firebase_app_distribution_login`
> Deprecate login action

- fastlane-plugin-firebase_app_distribution.gemspec
Attempt to fix broken image on https://www.rubydoc.info/gems/fastlane-plugin-firebase_app_distribution/
> Add fad-icon.png to spec.files

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- lib/fastlane/plugin/firebase_app_distribution/version.rb
- spec/firebase_app_distribution_api_client_spec.rb
Following-up from this issue: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/279, my team is still facing upload timeouts due to a combination of a large app and slow upload speed, so I took it upon myself to add support for a configurable timeout.
Please let me know if any of this doesn't follow your code standards, but the change passes the tests (both `rake` and `rubocop -a`).
I've tested this locally, by referencing my fork in my project's `Pluginfile`:
```
gem 'fastlane-plugin-firebase_app_distribution', git: 'https://github.com/spatenotte/fastlane-plugin-firebase_app_distribution.git', branch: 'sp/configurable-timeout'
```
And observed that passing the `upload_timeout` parameter to `firebase_app_distribution()` does increase the timeout as expected.
Not …
> Added configurable upload timeout to firebase_app_distribution_action

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_latest_release.rb
- spec/firebase_app_distribution_get_latest_release_spec.rb
We document `SharedVariable::FIREBASE_APP_DISTRO_LATEST_RELEASE` but it isn't actually defined.
This leads to a `[!] uninitialized constant Fastlane::Actions::SharedValues::FIREBASE_APP_DISTRO_LATEST_RELEASE (NameError)` error.
> Defined SharedVariables constant for FIREBASE_APP_DISTRO_LATEST_RELEASE

- .github/workflows/ruby.yml
Other versions fail with
```
wrong number of arguments (given 5, expected 1)
/opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/psych.rb:322:in `safe_load'
```
> Only test with ruby versions 2.7 and 3.0

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_remove_testers_action.rb
- spec/firebase_app_distribution_remove_testers_action_spec.rb
This removes the testers from only the specified group, but doesn't delete them from the project.
> Support `group_alias` parameter for `remove_testers_action`.

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_create_group_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_delete_group_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_latest_release.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_helper.rb
Example `User-Agent` header containing client information
```
User-Agent: fastlane/0.6.1 google-apis-firebaseappdistribution_v1/0.3.0 Mac OS X/13.4.1 (gzip)
```
> Support debug mode and client headers with generated API client

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_helper.rb
We were setting `RequestOptions.max_elapsed_time` but that only sets the maximum time including retries. We also need to set `Google::Apis::ClientOptions.default.send_timeout_sec` to give the actual POST more time to finish: https://github.com/googleapis/google-api-ruby-client/blob/4c6c8a1e7c4a177e62660b79b526fe914aefa7ae/google-apis-core/lib/google/apis/options.rb#L58-L59
> Set send_timeout on API client to fix upload_timeout param

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_auth_client.rb
- lib/fastlane/plugin/firebase_app_distribution/version.rb
- spec/firebase_app_distribution_action_spec.rb
- spec/firebase_app_distribution_auth_client_spec.rb
Reverts the switchover for uploads to the new client in https://github.com/firebase/fastlane-plugin-firebase_app_distribution/pull/318. This should address https://github.com/firebase/fastlane-plugin-firebase_app_distribution/issues/330.
Confirmed locally that it reduces upload times for a large binary from 120s down to 30s.
> Use old API client for uploads and bump to 0.7.2.pre.1

- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_auth_client.rb
- spec/firebase_app_distribution_auth_client_spec.rb
- Added validation to check whether it's an `external_account` or `service_account` to fix error `missing client_email` caused by https://github.com/googleapis/google-auth-library-ruby/blob/main/lib/googleauth/json_key_reader.rb#L24 when using Workload Identity Federation
- `service_account` –> `Google::Auth::ServiceAccountCredentials`
- `external_account` –> `Google::Auth::ExternalAccount::Credentials`
- Fix tests
> Validate credential account

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_add_testers_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_create_group_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_delete_group_action.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_latest_release.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_udids.rb
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_remove_testers_action.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_helper.rb
This is in preparation for actions which need both, the `v1` and `v1alpha` clients, and should call `init_google_api_client` and `get_authorization only` once.
> Inline `init_client`

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_udids.rb
- lib/fastlane/plugin/firebase_app_distribution/version.rb
- Don't throw an exception if there are no testers with UDIDs (fixes #362) - instead delete the UDID output file
- bump version to 0.9.0.pre.4
> Don't throw an exception if there are no testers with UDIDs

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/version.rb
- spec/firebase_app_distribution_action_spec.rb
Changes from API review:
- Add `test_password_file` option
- Change `test_async` to `test_non_blocking`
Also:
- Add environment variable options for all new options, which is useful at least for `test_password`
> Changes from API review (bump to 0.9.0.pre.5)

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_error_message.rb
- spec/firebase_app_distribution_action_spec.rb
Unlike all the other API calls, binary upload uses `client.http()`. The errors returned by that method are not as nicely string-ified, so this PR returns a nice permissions error message in the case of a 403, and otherwise explicitly prints out the `status_code` in the message. This addresses #374
> Better handle errors when uploading binary

- .rubocop.yml
- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- Call `to_sym` on `[lane_context[PLATFORM_NAME]` (hopefully fixes #376).
- Explicitly only support iOS and Android.
> Make sure `platform` is a symbol

- lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb
- lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_apis.rb
- lib/fastlane/plugin/firebase_app_distribution/version.rb
- spec/firebase_app_distribution_action_spec.rb
> Support `test_case_ids` and `test_case_ids_file`
